name: political_think
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^10.1.2
  firebase_core: ^2.15.1
  hooks_riverpod: ^2.3.10
  firebase_auth: ^4.9.0
  firebase_ui_auth: ^1.8.0
  google_sign_in: ^6.1.5
  font_awesome_flutter: ^10.5.0
  cloud_firestore: ^4.9.1
  json_serializable: ^6.7.1
  flutter_spinkit: ^5.2.0
  cloud_functions: ^4.4.0
  receive_sharing_intent: ^1.4.5
  modal_bottom_sheet: ^3.0.0-pre
  any_link_preview: ^3.0.1
  shared_preferences: ^2.2.1
  uuid: ^3.0.7
  super_clipboard: ^0.6.4
  shimmer: ^3.0.0
  riverpod_infinite_scroll: ^1.0.9
  infinite_scroll_pagination: ^3.2.0
  flutter_svg: ^2.0.7
  ogp_data_extract: ^0.1.4
  chatview: ^1.3.1
  scroll_to_index: ^3.0.1
  linked_scroll_controller: ^0.2.0
  tuple: ^2.0.2
  equatable: ^2.0.5
  photo_view: ^0.14.0
  visibility_detector: ^0.4.0+2
  flutter_link_previewer: ^3.2.2
  flutter_parsed_text: ^2.2.1
  diffutil_dart: ^4.0.0
  date_count_down: ^3.0.0
  flutter_countdown_timer: ^4.1.0
  flutter_joystick: ^0.0.4
  google_fonts: ^6.1.0
  syncfusion_flutter_maps: ^24.1.41
  countries_world_map: ^1.1.1
  google_maps_flutter: ^2.5.0
  http: ^1.1.2
  syncfusion_flutter_sliders: ^24.1.44
  flutter_xlider: ^3.5.0
  syncfusion_flutter_core: ^24.1.44
  country_picker: ^2.0.23
  country_flags: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/maps/dark_map.json

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
  - family: Hackney
    fonts:
      - asset: assets/fonts/hackney.ttf
