name: political_think
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^10.1.2
  firebase_core: ^2.15.1
  hooks_riverpod: ^2.3.10
  firebase_auth: ^4.9.0
  firebase_ui_auth: ^1.8.0
  google_sign_in: ^6.1.5
  font_awesome_flutter: ^10.5.0
  cloud_firestore: ^4.9.1
  json_serializable: ^6.7.1
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6  
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

