name: Update GCS
on:
  push: 
    branches: [ "main" ]
    paths: 
      - 'functions/ai/**'
      - '.github/workflows/storage.yaml'

jobs:
  archive_training_data:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GH_SA_GOOGLE_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: 'Move GCS file'
      run: |
        DATE=$(date +%Y-%m-%d-%H-%M-%S)
        if gsutil -q stat gs://political-think.appspot.com/training/fine_tune.jsonl; then
          gsutil mv gs://political-think.appspot.com/training/fine_tune.jsonl gs://political-think.appspot.com/training/fine_tune-$DATE.jsonl
          echo "File moved successfully."
        else
          echo "File not found. No action taken."
        fi